config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    sleep 1
    @incomplete_tasks = Task.where(complete: false)
    @complete_tasks   = Task.where(complete: true)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.create!(task_params)
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.update_attributes!(task_params)
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskAjax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.check_box :complete, class: "hidden-checkbox" %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :complete, class: "task_cell" %>
  <%= f.submit "Update", class: "task_cell" %>
  <%= f.label :complete, task.content, class: (task.complete ? "done" : "") %>
  <%= link_to "(remove)", task, method: :delete, class: "remove", remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck(); 

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Checklist</h1>

<%= link_to 'New Task', new_task_path, id: "new_link", remote: true %>

<h2>To Do</h2>

<div class="tasks" id="incomplete_tasks">
  <%= render @incomplete_tasks %>
</div>

<h2>Done</h2>

<div class="tasks" id="complete_tasks">
  <%= render @complete_tasks %>
</div>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');
$('#task_content').focus(); 

app/views/tasks/update.js.erb
<% if @task.complete? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks').addClass('done');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks').removeClass("done");
<% end %>